name: Build for Multiple Platforms

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target:
          - aarch64-unknown-linux-gnu  # ARM 64-bit Linux
          - x86_64-unknown-linux-gnu   # 64-bit Linux
          - x86_64-pc-windows-gnu      # 64-bit Windows
          - x86_64-apple-darwin        # 64-bit macOS

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true

    - name: Add Targets
      run: rustup target add ${{ matrix.target }}

    - name: Build Binary
      run: cargo build --target ${{ matrix.target }} --release

    - name: Upload Binary Artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.target }}-binary
        path: target/${{ matrix.target }}/release/taskbuddy
