name: Build TaskBuddy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust and target
        run: |
          rustup target add aarch64-unknown-linux-gnu
          sudo apt-get update
          sudo apt-get install gcc-aarch64-linux-gnu -y

      - name: Build for aarch64
        run: cargo build --target aarch64-unknown-linux-gnu --release
